### ISSUE TITLE
rename this package to TIFFFiles?

### ISSUE THREAD

**Issue by johnnychen94** [tlnagy/TIFF.jl#5]
Yes it's a bit weird for TIFFFiles, but there was a discussion on names when registering PNGFiles

https://github.com/JuliaRegistries/General/pull/9508

**Comment by tlnagy** [comment]
TIFFFiles is pretty clunky, I'm not that enamored with any of the names suggested in that thread. What about `TaggedImages.jl`? Because (besides the basic TIFF IO) this package has types for associating data with slices of a 3D array.

@ianshmean, @DilumAluthge, @timholy thoughts?

**Comment by timholy** [comment]
I worry that TaggedImages won't be easily discoverable, it depends on having the fact that TIFF=tagged image file format at the tip of your tongue.

**Comment by ianshmean** [comment]
Having TIFF in the name seems like a good idea, but for FileIO purposes, if the user tries to load a `.tiff` they'll be told to install `ImageIO` so the name won't be visible to them, so discoverability seems more of an advanced user issue?

It's really unfortunate that TIFFFiles feels clunky. I thought it was just quirky.. but it is mildly frustrating to check that there are enough F's in there.

Maybe TIFF is fine as it is? I mean, the acronym does already include "Files"

**Comment by DilumAluthge** [comment]
Personally, I’d recommend something like this:
- `TIFFFiles.jl`
- `TIFFImages.jl`
- `TiffFiles.jl`
- `TiffImages.jl`

I really want to avoid adding new packages to General that are just acronyms/initialisms. Especially if the package name is relatively short.

**Comment by tlnagy** [comment]
So I've come around on this and I think the least clunky name is @DilumAluthge's suggestion of `TIFFImages.jl`. Additionally, I agree with @ianshmean that most people probably won't need to even know about this package (unless there's a bug :cold_sweat:). Also given that the Julia package manager autocompletes package names, discoverability wouldn't be too bad since you could just type `julia> add TIFF<tab>` to find it.
