### ISSUE TITLE
ERROR: KeyError: key (TIFF.SAMPLEFORMAT_INT, 0x0008) not found

### ISSUE THREAD

**Issue by JiangXL** [tlnagy/TIFF.jl#7]
One more error might need to be caught.
`4D-series.ome.tif` is sample file from [OME-TIFF website]( https://docs.openmicroscopy.org/ome-model/6.0.0/ome-tiff/data.html).

```julia
julia> TIFF.load("4D-series.ome.tif")
ERROR: KeyError: key (TIFF.SAMPLEFORMAT_INT, 0x0008) not found
Stacktrace:
 [1] getindex(::Dict{Tuple{TIFF.SampleFormats,Int64},DataType}, ::Tuple{TIFF.SampleFormats,UInt16}) at ./dict.jl:477
 [2] output(::TIFF.IFD{UInt32}) at /home/hf/.julia/dev/TIFF/src/ifds.jl:113
 [3] load(::String) at /home/hf/.julia/dev/TIFF/src/load.jl:14
 [4] top-level scope at REPL[2]:1
```

**Comment by tlnagy** [comment]
This is known limitation. I have a branch adding support for integers (not just unsigned ints and floats), but I haven't figured out how to handle the sign for display. I can't simply display the values as `Gray`s because of potential negative numbers.

1. I can remove the sign and represent the data as a `Gray{Normed{UInt8, 7}}` which is likely how other libraries handle this

2. I can return a RGB image using [`ImageCore.colorsigned`](https://juliaimages.org/latest/function_reference/#ImageCore.colorsigned) to map positive or negative values to magenta or green, respectively. This way they are distinguishable. I would likely need to do this lazily so that the underlying integer array is easily accessible. Maybe @timholy has thoughts?

**Comment by tlnagy** [comment]
Hi @JiangXL, this is now fixed in the latest master of `TIFF.jl`. If you're still interested, you can take it for a spin!

**Comment by JiangXL** [comment]
Great to hear that! I'll try it later.
